module.exports = {
    globals: {
        "$": false,
        "$$": false,
        "Browser": false,
        "Chain": false,
        "Class": false,
        "Cookie": false,
        "Core": false,
        "Document": false,
        "DomReady": false,
        "DOMEvent": false,
        "DOMReady": false,
        "Element": false,
        "Elements": false,
        "Event": false,
        "Events": false,
        "Fx": false,
        "Hash": false,
        "IFrame": false,
        "instanceOf": false,
        "MooTools": false,
        "Native": false,
        "Options": false,
        "Request": false,
        "Selectors": false,
        "Slick": false,
        "Type": false,
        "typeOf": false,
        "Window": false
    }
};
